name: Demo 3

on:
  workflow_dispatch:    
    inputs:
      name:
        description: 'environment'
        default: ''
        required: true

jobs:
  
  job1:
    runs-on: ubuntu-latest
    environment: DEMO_DEV
    steps:
    - name: job1
      run: echo "Job 1 - Hello"
      
  job2:
    runs-on: ubuntu-latest
    environment: DEMO_QA
    needs:
      - job1
    steps:
    - name: job2
      run: echo "Job 2 - Hello"
      
  job3:
    runs-on: ubuntu-latest
    needs:
      - job2
    steps:
    - name: job3
      run: echo "Job 3 - Hello"
      
  job4:
    runs-on: ubuntu-latest
    environment: DEMO_PROD
    needs:
      - job2
    steps:
    - name: job4
      run: echo "Job 4 - Hello"
